/**
 * Regenerate the measured-figures section of docs/MEASUREMENTS.md from the
 * database, and the offline CENSUS_FALLBACK snapshot in src/lib/data.ts.
 *
 * The document previously carried figures typed by hand. They were accurate when
 * written and went stale within hours as the census advanced - the same fault
 * that was fixed twice in the application. A document whose entire claim is
 * "measured, not asserted" cannot contain assertions.
 *
 * The fallback snapshot is the same fault in source form: a dated copy of the
 * funnel that only loads when the database is unreachable, but which drifted
 * 11 days behind before anyone noticed. It regenerates here between GENERATED
 * markers, on the same schedule, so demo mode tracks reality too.
 *
 * Only the blocks between the GENERATED markers are rewritten. Everything else -
 * method, known defects, the marketplace analysis, the corrections to earlier
 * conclusions - is prose and stays under human control.
 *
 * Run: npx tsx scripts/write-measurements.ts
 */
import "dotenv/config";
import postgres from "postgres";
import { readFileSync, writeFileSync } from "node:fs";

const FILE = "docs/MEASUREMENTS.md";
const BEGIN = "<!-- BEGIN GENERATED: measured figures -->";
const END = "<!-- END GENERATED -->";
const DATA_FILE = "src/lib/data.ts";
const FB_BEGIN = "// BEGIN GENERATED: census fallback";
const FB_END = "// END GENERATED";

const sql = postgres(process.env.DATABASE_URL!, { prepare: false, max: 2, onnotice: () => {} });

const n = (v: unknown) => Number(v ?? 0).toLocaleString();
const pct = (a: unknown, b: unknown) => {
  const x = Number(a ?? 0), y = Number(b ?? 0);
  return y > 0 ? `${((x / y) * 100).toFixed(2)}%` : "—";
};

try {
  const censusRows = await sql<any[]>`select * from census_stats where id = 'bsc'`;
  const c = censusRows[0];
  if (!c) throw new Error("census_stats has no row; run scripts/sync-registry.ts first");

  const cats = await sql<any[]>`
    select category, count(*)::int as total,
           count(*) filter (where trust_state = 'VERIFIED')::int as verified
    from agents where chain_id = 56 and category is not null
    group by category order by total desc
  `;
  const states = await sql<any[]>`
    select trust_state, count(*)::int as n from agents where chain_id = 56
    group by trust_state order by n desc
  `;
  const ops = await sql<any[]>`
    select label, agent_count, validated_count, fatal_defect_count
    from operators where agent_count > 0 order by agent_count desc limit 10
  `;
  const opps = await sql<any[]>`
    select category, count(*)::int as total, count(*) filter (where eligible)::int as eligible
    from opportunities where chain_id = 56 group by category order by category
  `;
  const probes = await sql<any[]>`
    select count(*)::int as total,
           count(*) filter (where grade = 'validated')::int as validated,
           count(distinct endpoint_id)::int as endpoints
    from probes_raw
  `;
  const p = probes[0] ?? {};
  const [size] = await sql<any[]>`select pg_size_pretty(pg_database_size(current_database())) as s`;

  const JUDGED = new Set(["rebalancing", "grid", "yield", "health"]);
  const judged = cats.filter((x) => JUDGED.has(x.category));
  const other = cats.filter((x) => !JUDGED.has(x.category));
  const sum = (rows: any[], k: string) => rows.reduce((t, r) => t + Number(r[k] ?? 0), 0);

  const schemes = (c.uri_schemes ?? {}) as Record<string, number>;
  const kinds = (c.endpoint_kinds ?? {}) as Record<string, number>;

  const measuredAt = c.measured_at ? new Date(c.measured_at).toISOString().replace("T", " ").slice(0, 19) : "unknown";

  const lines: string[] = [];
  lines.push(BEGIN);
  lines.push("");
  lines.push(`> Regenerated by \`scripts/write-measurements.ts\` from the database. Do not edit by`);
  lines.push(`> hand: the figures move continuously and any typed copy goes stale within hours.`);
  lines.push(`> **Census measured at ${measuredAt} UTC.**`);
  lines.push("");

  lines.push(`## Registry census`);
  lines.push("");
  lines.push(`Read directly from the ERC-8004 Identity Registry at \`${c.registry}\` on BNB Smart`);
  lines.push(`Chain, by multicall rather than through a rate-limited API.`);
  lines.push("");
  lines.push("```");
  lines.push(`${n(c.tokens_minted).padStart(9)}   identities minted`);
  lines.push(`${n(c.censused).padStart(9)}   censused                        ${pct(c.censused, c.tokens_minted)} of the registry`);
  lines.push(`${n(c.resolved).padStart(9)}   registration file resolved      ${pct(c.resolved, c.censused)} of censused`);
  lines.push(`${n(c.named).padStart(9)}   carry a name                    ${pct(c.named, c.resolved)} of resolved`);
  lines.push(`${n(c.claim_active).padStart(9)}   self-declare "active": true     ${pct(c.claim_active, c.resolved)} of resolved`);
  lines.push(`${n(c.with_endpoint).padStart(9)}   declare ANY service endpoint    ${pct(c.with_endpoint, c.resolved)} of resolved`);
  lines.push(`${n(c.callable).padStart(9)}   callable and lint-clean         ${pct(c.callable, c.resolved)} of resolved`);
  lines.push("```");
  lines.push("");
  const gap = Number(c.claim_active ?? 0) - Number(c.with_endpoint ?? 0);
  lines.push(`> **${n(gap)} identities declare themselves active while publishing no endpoint of any`);
  lines.push(`> kind.** \`"active": true\` is self-reported, unverified, and asserted by`);
  lines.push(`> ${pct(c.claim_active, c.resolved)} of resolved registrations against ${pct(c.with_endpoint, c.resolved)} that`);
  lines.push(`> declare somewhere to be reached. It is the least informative field in the`);
  lines.push(`> standard, and any directory presenting it as liveness is repeating a claim`);
  lines.push(`> rather than reporting a fact.`);
  lines.push("");

  lines.push(`### Metadata pointer distribution`);
  lines.push("");
  lines.push(`| Scheme | Count | Share |`);
  lines.push(`| --- | --- | --- |`);
  for (const [k, v] of Object.entries(schemes).sort((a, b) => b[1] - a[1])) {
    lines.push(`| \`${k}\` | ${n(v)} | ${pct(v, c.censused)} |`);
  }
  lines.push("");
  lines.push(`\`data:\` pointers resolve from calldata with no network call. \`${n(schemes.empty ?? 0)}\``);
  lines.push(`identities were registered with no metadata pointer at all.`);
  lines.push("");

  lines.push(`### Concentration: ownership versus infrastructure`);
  lines.push("");
  lines.push(`| Ownership | | Infrastructure | |`);
  lines.push(`| --- | --- | --- | --- |`);
  lines.push(`| Distinct owners | **${n(c.owners)}** | Distinct endpoint operators | **${n(c.operators)}** |`);
  lines.push(`| Holding exactly one | ${n(c.owners_with_one_agent)} | Largest operator's share | **${c.largest_operator_share}%** |`);
  lines.push(`| Top 10 owners combined | ${c.top10_owner_share}% | Top 5 operators | ${c.top5_operator_share}% |`);
  lines.push(`| Mean per owner | ${(Number(c.censused) / Math.max(Number(c.owners), 1)).toFixed(1)} | Top 20 operators | ${c.top20_operator_share}% |`);
  lines.push("");
  lines.push(`> **${n(c.owners)} wallets registered an identity. ${n(c.operators)} organisations run`);
  lines.push(`> infrastructure.** Ownership is not concentrated, which is the signature of points`);
  lines.push(`> farming rather than supply. Concentration lives in *endpoints*, and only an`);
  lines.push(`> endpoint-derived operator identity reveals it: ranking by owner address would`);
  lines.push(`> present ${n(c.owners)} apparently independent suppliers.`);
  lines.push("");

  if (ops.length) {
    lines.push(`| Operator | Agents | Verified | Fatal defects |`);
    lines.push(`| --- | --- | --- | --- |`);
    for (const o of ops) {
      lines.push(`| \`${o.label}\` | ${n(o.agent_count)} | ${n(o.validated_count)} | ${n(o.fatal_defect_count)} |`);
    }
    lines.push("");
  }

  lines.push(`### Liveness, measured by this project`);
  lines.push("");
  lines.push(`| | |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Probes recorded | ${n(p.total)} |`);
  lines.push(`| Distinct endpoints probed | ${n(p.endpoints)} |`);
  lines.push(`| Completed a protocol handshake | ${n(p.validated)} |`);
  for (const s of states) lines.push(`| Agents \`${s.trust_state}\` | ${n(s.n)} |`);
  lines.push("");
  lines.push(`A handshake means an A2A card parsed and validated, or an MCP \`initialize\``);
  lines.push(`returned a usable result. An HTTP 200 alone proves a server answered, not that`);
  lines.push(`an agent exists behind it.`);
  lines.push("");

  lines.push(`### Capability classification`);
  lines.push("");
  lines.push(`${n(sum(cats, "total"))} agents classified across ${cats.length} categories,`);
  lines.push(`${n(sum(cats, "verified"))} of them verified.`);
  lines.push("");
  lines.push(`| Category | Required | Agents | Verified |`);
  lines.push(`| --- | --- | --- | --- |`);
  for (const x of [...judged, ...other]) {
    lines.push(`| ${x.category} | ${JUDGED.has(x.category) ? "**yes**" : "no"} | ${n(x.total)} | ${n(x.verified)} |`);
  }
  lines.push("");
  lines.push(`Only **${n(sum(judged, "total"))}** agents in the registry verifiably do one of the four`);
  lines.push(`required jobs. That is the measured state of the chain, not a limit of the`);
  lines.push(`matching: a category is assigned only on specific evidence, and every assignment`);
  lines.push(`stores the terms that produced it.`);
  lines.push("");

  if (opps.length) {
    lines.push(`### Opportunity surface, indexed from chain`);
    lines.push("");
    lines.push(`| Category | Rows | Eligible |`);
    lines.push(`| --- | --- | --- |`);
    for (const o of opps) lines.push(`| ${o.category} | ${n(o.total)} | ${n(o.eligible)} |`);
    lines.push("");
    lines.push(`Indexed from live PancakeSwap V3 pool state and Venus market state, so each`);
    lines.push(`required category holds real work whether or not a competent agent exists.`);
    lines.push("");
  }

  lines.push(`Database size: ${size?.s ?? "unknown"}.`);
  lines.push("");
  lines.push(END);

  const doc = readFileSync(FILE, "utf8");
  const start = doc.indexOf(BEGIN);
  const finish = doc.indexOf(END);

  let out: string;
  if (start >= 0 && finish > start) {
    out = doc.slice(0, start) + lines.join("\n") + doc.slice(finish + END.length);
  } else {
    // First run: insert after the document's opening paragraph.
    const anchor = doc.indexOf("\n## ");
    const head = anchor > 0 ? doc.slice(0, anchor) : doc;
    const tail = anchor > 0 ? doc.slice(anchor) : "";
    out = `${head}\n\n${lines.join("\n")}\n${tail}`;
  }

  writeFileSync(FILE, out, "utf8");
  console.log(`\n  wrote ${FILE}`);
  console.log(`  generated block: ${lines.length} lines`);
  console.log(`  census measured at ${measuredAt} UTC`);

  // ── offline fallback snapshot in src/lib/data.ts ────────────────────────
  // The GitHub Action runs `npx tsc --noEmit` before committing, so a malformed
  // write here fails the job loudly instead of breaking master silently.
  // Every integer is emitted with underscore separators: "12,220" in TS source
  // is a comma expression that evaluates to 220 - silently wrong, the exact
  // failure class this project exists to catch.
  const u = (v: unknown) =>
    Number(v ?? 0).toString().replace(/\B(?=(\d{3})+(?!\d))/g, "_");
  const numOr = (v: unknown, d: number) => (v == null ? d : Number(v));
  const fbSchemes = Object.entries(schemes)
    .sort((a, b) => b[1] - a[1])
    .map(([k, v]) => `${k}: ${u(v)}`)
    .join(", ");
  const fbKinds = Object.entries(kinds)
    .sort((a, b) => b[1] - a[1])
    .map(([k, v]) => `${k}: ${u(v)}`)
    .join(", ");
  const fbLines = [
    "export const CENSUS_FALLBACK = {",
    `  tokensMinted: ${u(c.tokens_minted)},`,
    `  censused: ${u(c.censused)},`,
    `  resolved: ${u(c.resolved)},`,
    `  named: ${u(c.named)},`,
    `  claimActive: ${u(c.claim_active)},`,
    `  withEndpoint: ${u(c.with_endpoint)},`,
    `  callable: ${u(c.callable)},`,
    `  operators: ${u(c.operators)},`,
    `  owners: ${u(c.owners)},`,
    `  ownersWithOneAgent: ${u(c.owners_with_one_agent)},`,
    `  largestOperatorShare: ${numOr(c.largest_operator_share, 0)},`,
    `  top5OperatorShare: ${numOr(c.top5_operator_share, 0)},`,
    `  top10OwnerShare: ${numOr(c.top10_owner_share, 0)},`,
    `  declaresReputationTrust: ${u(c.declares_reputation)},`,
    `  emptyTokenUri: ${u(c.empty_token_uri)},`,
    `  x402Supported: ${u(c.x402_supported)},`,
    `  fatalDefects: ${u(c.fatal_defects)},`,
    `  uriSchemes: { ${fbSchemes} } as Record<string, number>,`,
    `  endpointKinds: { ${fbKinds} } as Record<string, number>,`,
    `  topOperators: [] as { domain: string; endpoints: number; callable: number }[],`,
    `  measuredAt: "${measuredAt.slice(0, 10)}",`,
    `  registry: "${c.registry}",`,
    "} as const;",
  ];

  const src = readFileSync(DATA_FILE, "utf8");
  const fbStart = src.indexOf(FB_BEGIN);
  const fbFinish = src.indexOf(FB_END, fbStart);
  if (fbStart >= 0 && fbFinish > fbStart) {
    const next = src.slice(0, fbStart + FB_BEGIN.length) + "\n" + fbLines.join("\n") + "\n" + src.slice(fbFinish);
    writeFileSync(DATA_FILE, next, "utf8");
    console.log(`  refreshed ${DATA_FILE} fallback snapshot (${measuredAt.slice(0, 10)})`);
  } else {
    console.log(`  WARN: ${FB_BEGIN} markers not found in ${DATA_FILE}; snapshot not refreshed`);
    process.exitCode = 1;
  }
  console.log("");
} catch (e: any) {
  console.error(`\n  FAILED: ${String(e?.message ?? e).slice(0, 240)}\n`);
  process.exitCode = 1;
} finally {
  await sql.end({ timeout: 5 });
}
