-- GEBO 0003 — lean per-token registry table.
--
-- Why: the funnel figures (270,200 minted / 155,304 resolved / 153,454 claiming
-- active / 759 with an endpoint) covered the whole registry but were derived
-- from a 144 MB local NDJSON file. That file cannot exist in CI, so a scheduled
-- refresh had no source, and the numbers could only be regenerated by hand on
-- one machine.
--
-- Storing seven narrow columns per token instead makes the funnel a live SQL
-- aggregate and lets the census run incrementally — only tokens above the
-- high-water mark need reading, which is a few hundred a day rather than 270k.
--
-- Deliberately NOT the `agents` table: that holds rich rows for the ~21k
-- endpoint-bearing agents that are actually browsable. This is the thin census
-- ledger for all 270k, and at ~40 MB it leaves ample headroom.

create table if not exists public.registry_tokens (
  token_id        bigint primary key,
  owner           text,
  uri_scheme      text,          -- data | https | ipfs | http | empty | other
  resolved        boolean not null default false,
  has_name        boolean not null default false,
  claim_active    boolean not null default false,
  endpoint_count  smallint not null default 0,
  callable        boolean not null default false,
  has_fatal       boolean not null default false,
  x402            boolean not null default false,
  trust_models    text[],
  operator_domain text,
  checked_at      timestamptz not null default now()
);

create index if not exists registry_tokens_scheme_idx    on public.registry_tokens (uri_scheme);
create index if not exists registry_tokens_callable_idx  on public.registry_tokens (callable) where callable;
create index if not exists registry_tokens_endpoint_idx  on public.registry_tokens (endpoint_count) where endpoint_count > 0;
create index if not exists registry_tokens_operator_idx  on public.registry_tokens (operator_domain);

alter table public.registry_tokens enable row level security;
drop policy if exists registry_tokens_public_read on public.registry_tokens;
create policy registry_tokens_public_read on public.registry_tokens
  for select to anon, authenticated using (true);

-- Recompute census_stats from registry_tokens. Called by the sync job so the
-- funnel is derived from stored rows rather than transcribed by a human.
create or replace function public.refresh_census_stats()
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_total        bigint;
  v_endpoints    bigint;
begin
  select count(*) into v_total from registry_tokens;
  select coalesce(sum(endpoint_count), 0) into v_endpoints from registry_tokens;

  insert into census_stats as cs (
    id, chain_id, registry,
    tokens_minted, censused, resolved, named, claim_active, with_endpoint, callable,
    operators, owners, owners_with_one_agent,
    largest_operator_share, top5_operator_share, top20_operator_share, top10_owner_share,
    declares_reputation, empty_token_uri, x402_supported, fatal_defects,
    uri_schemes, endpoint_kinds, trust_models, top_operators,
    measured_at, updated_at
  )
  select
    'bsc', 56, '0x8004a169fb4a3325136eb29fa0ceb6d2e539a432',
    (select coalesce(max(token_id), 0) from registry_tokens),
    v_total,
    (select count(*) from registry_tokens where resolved),
    (select count(*) from registry_tokens where has_name),
    (select count(*) from registry_tokens where claim_active),
    (select count(*) from registry_tokens where endpoint_count > 0),
    (select count(*) from registry_tokens where callable),
    (select count(distinct operator_domain) from registry_tokens where operator_domain is not null),
    (select count(distinct owner) from registry_tokens where owner is not null),
    (select count(*) from (
        select owner from registry_tokens where owner is not null
        group by owner having count(*) = 1) s),
    (select round(coalesce(100.0 * max(c) / nullif(v_endpoints, 0), 0), 2) from (
        select sum(endpoint_count) as c from registry_tokens
        where operator_domain is not null group by operator_domain) a),
    (select round(coalesce(100.0 * sum(c) / nullif(v_endpoints, 0), 0), 2) from (
        select sum(endpoint_count) as c from registry_tokens
        where operator_domain is not null group by operator_domain
        order by 1 desc limit 5) b),
    (select round(coalesce(100.0 * sum(c) / nullif(v_endpoints, 0), 0), 2) from (
        select sum(endpoint_count) as c from registry_tokens
        where operator_domain is not null group by operator_domain
        order by 1 desc limit 20) d),
    (select round(coalesce(100.0 * sum(c) / nullif(v_total, 0), 0), 2) from (
        select count(*) as c from registry_tokens
        where owner is not null group by owner order by 1 desc limit 10) e),
    (select count(*) from registry_tokens where 'reputation' = any(trust_models)),
    (select count(*) from registry_tokens where uri_scheme = 'empty'),
    (select count(*) from registry_tokens where x402),
    (select count(*) from registry_tokens where has_fatal),
    (select coalesce(jsonb_object_agg(uri_scheme, n), '{}'::jsonb) from (
        select uri_scheme, count(*) as n from registry_tokens
        where uri_scheme is not null group by uri_scheme) f),
    (select coalesce(jsonb_object_agg(kind, n), '{}'::jsonb) from (
        select kind, count(*) as n from agent_endpoints where chain_id = 56 group by kind) g),
    (select coalesce(jsonb_object_agg(tm, n), '{}'::jsonb) from (
        select tm, count(*) as n from (
          select unnest(trust_models) as tm from registry_tokens) h
        where tm is not null and tm <> '' group by tm order by 2 desc limit 12) i),
    (select coalesce(jsonb_agg(jsonb_build_object(
        'domain', operator_domain, 'endpoints', eps, 'callable', callables)
        order by eps desc), '[]'::jsonb) from (
        select operator_domain,
               sum(endpoint_count) as eps,
               count(*) filter (where callable) as callables
        from registry_tokens where operator_domain is not null
        group by operator_domain order by 2 desc limit 15) j),
    now(), now()
  on conflict (id) do update set
    tokens_minted = excluded.tokens_minted,
    censused = excluded.censused,
    resolved = excluded.resolved,
    named = excluded.named,
    claim_active = excluded.claim_active,
    with_endpoint = excluded.with_endpoint,
    callable = excluded.callable,
    operators = excluded.operators,
    owners = excluded.owners,
    owners_with_one_agent = excluded.owners_with_one_agent,
    largest_operator_share = excluded.largest_operator_share,
    top5_operator_share = excluded.top5_operator_share,
    top20_operator_share = excluded.top20_operator_share,
    top10_owner_share = excluded.top10_owner_share,
    declares_reputation = excluded.declares_reputation,
    empty_token_uri = excluded.empty_token_uri,
    x402_supported = excluded.x402_supported,
    fatal_defects = excluded.fatal_defects,
    uri_schemes = excluded.uri_schemes,
    endpoint_kinds = excluded.endpoint_kinds,
    trust_models = excluded.trust_models,
    top_operators = excluded.top_operators,
    measured_at = excluded.measured_at,
    updated_at = now();
end;
$$;
